[package]
name = "reflectionnnn/networker"
description = "Service based networker."
license = "MIT"
version = "0.1.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
