[package]
name = "reflectionnnn/networker"
description = "Service based networker."
authors = ["Reflection"]
license = "MIT"
version = "0.1.4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["src", "LICENSE"]

[dependencies]
